### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by rugk** [werthdavid/kjua#3]
You've added quite some commits lately, is there a new release planned? :smiley: (last one was still in 2019)

**Comment by werthdavid** [comment]
In fact I did create a new release. I migrated to the latest svg.js (library) because there seemed to be some problems in the upstream project ngx-kjua with the latest version of Angular. Do you miss anything or are there any issues with your extension? Any ideas for new cool features?

**Comment by rugk** [comment]
The only thing I did miss is to have the release appear on https://github.com/werthdavid/kjua/releases, i.e. tag and release it on GItHub too, please. :smiley:
