### ISSUE TITLE
Do not use eval & innerHtml functions

### ISSUE THREAD

**Issue by rugk** [werthdavid/kjua#4]
When the add-on is linted for inclusion in Firefox add-on store, we get some warnings, because of `eval` functions being used.

The source is https://unpkg.com/kjua-svg@1.10.0/kjua.min.js

Here is the full downstream report: https://github.com/rugk/offline-qr-code/issues/248

It would be good, and it's best security practice, to never use `eval` or similar. Not only for add-ons, also because strong [CSP](https://content-security-policy.com/) prevent the usage/execution of `eval` in these contexts.
`innerHtml` can also lead to code execution, that's why it's treated the same…

AFAIK in the upstream, not forked `kjua` these never appeared…

**Comment by werthdavid** [comment]
innerHtml is used for the svg-rendering but what's the alternative here?

**Comment by rugk** [comment]
See https://extensionworkshop.com/documentation/develop/build-a-secure-extension/ and https://developer.mozilla.org/de/docs/Mozilla/Add-ons/WebExtensions/Content_Security_Policy#Default_content_security_policy

In most cases you could e.g. use textNode for text-only or you need to use teh JS APIs for building the DOM manually…

**Comment by werthdavid** [comment]
I understand that but the thing is that "qrcode-generator" only gives me a string that looks like "<svg ..../>" so what is the alternative of innerHtml? To me the warning looks like a false positive, I don't see a possibility to "inject" something bad here.

**Comment by rugk** [comment]
Well… it's not a false-positive, it's surely an issue – the thing is the library could return [an SVGELement](https://developer.mozilla.org/docs/Web/API/SVGElement) e.g. instead of a string with an SVG or so. [Created like this, somehow](https://support.mozilla.org/en-US/questions/888633#answer-264793).

**Comment by werthdavid** [comment]
Where do you see the possibility that a user can "inject" something there and misuse innerHtml? Like I said, the library that generates the QR-code returns an SVG-string so I don't understand how "createElementNS" helps here? Feel free to open a PR though!

**Comment by rugk** [comment]
Okay you mean that with a "false-positive".
So first: The user could possibly inject something, as of course the text is usually provided by them somehow. 
So we do have, theoretically, an attack vector here.

So what you mean with "false-positive" is: It does not lead to a security issue. This may even be true and I may agree, but it's not what add-on linters/CSP etc. is about.
Because you use these features to reduce the attack vector, disallow _potential_ unsafe functions and enforce best practises.
Always remember that you don't know the vulnerabilities before you see them…
And there are  [a lot of arguments not to use  `eval` e.g.](https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/eval#Never_use_eval!).
That's why I did not call it a false-positive: It is valid, if it detects a "potential flaw/potentially insecure feature that may have a bad security impact". It's a linter after all… it cannot evaluate whether that security impact is really "true".

Sooo… that all said, I get your point that if you get an SVG string, it is hard to change all the internals so it does not do this. I get it, and Mozilla reviewers also seem to accept this as a common lib / this potential problem. (it's also only a "warning" on their website, not an error preventing you to submit your code)

----

However so far we only talked about `innerHtml`. If you see the full report https://github.com/rugk/offline-qr-code/issues/248 you also sometimes use `eval` or `Function` (= which is basically the same as `eval`) apparently.
Generally, there are multiple lines where these features are used – which, theoretically, increases the attack surface and may have performance influences etc.

Also, IIRC in my last submission there were not soo many errors, so this may have been a new thing introduced by some commits… :thinking: (or it is somehow only in the minified version hmm…)

**Comment by rugk** [comment]
So I'm looking into the file https://unpkg.com/kjua-svg@1.10.0/kjua.min.js again:
* If I search for `Function` (whole word + case sensitive) in it, I find 6 results
* 0x `eval`
* 4x `innerHTML`

**Comment by werthdavid** [comment]
`innerHTML` is only used within the svg-rendering and `Function` is not used at all so it seems to be an issue with the mysterious undocumented build-tool that is used by the original kjua. Maybe Webpack is an alternative?

Like I said before, I'm always happy if there is a PR as a basis for a discussion

**Comment by rugk** [comment]
> Maybe Webpack is an alternative?

I guess webpack is always an alternative. At least it's well known…

> the mysterious undocumented build-tool that is used by the original kjua

That sounds… ehm… well… not so good… :see_no_evil:

**Comment by rugk** [comment]
Ah, just noticed upstream had the same issue (though not that often). See https://github.com/lrsjng/kjua/issues/14#issuecomment-663838148
